### ISSUE TITLE
Greetings msg

### ISSUE THREAD

**Issue by d4n1elchen** [ccns/quiz-chatbot-fb#1]
FB審查會測試歡迎訊息⋯

**Comment by Yuessiah** [comment]
(　′∀`)σ≡σ☆))Д′)
&nbsp;^^^&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^
&nbsp;FB&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DC

**Comment by d4n1elchen** [comment]
49e3f70a31c49b98340a2915f7deeaff7684440b
